config/routes.rb
PurexNew::Application.routes.draw do


  root :to => 'home#index'
  get "taxes/irs_income" => "taxes#irs_income", as: :taxes_income

  get "payouts/create"

  get "dashboard/payouts(/:status)" => "dashboard#payouts", :as => :dashboard_payouts
  get "dashboard(/:detail)" => 'dashboard#index', :as => :dashboard_detail

  post "tags/create" => "tags#create", :as => :annotate
  match "tags/destroy" => "tags#destroy", :as => :destroy_tag, via: [:get, :delete, :post]

  resources :payments, :only => [:create]
  get "/validate_coupon" => "payments#validate_coupon", :as => :validate_coupon, via: [:get]
  get "appraisal_data/create"
  get '/facebook/' => "users#facebook_login", via: [:get]
  match '/users/update_appraiser_status' => "users#update_appraiser_status", :as => :update_appraiser_status, via: [:post, :put]
  get '/users/get_user_by_vendor_token' => 'users#get_user_by_vendor_token'

  devise_for :users, :controllers => { :registrations => "registrations"}

  devise_for :appraisers, :controllers => { :registrations => "registrations"}

  devise_for :customers, :controllers => {:omniauth_callbacks => "omniauth_callbacks",  :registrations => "registrations"}

  match '/users/:id/finish_signup' => 'users#finish_signup', via: [:get, :patch], :as => :finish_signup

    post '/users/save_json_signature' => 'users#save_json_signature', :as => :save_json_signature
    get '/users/new_signature' => 'users#new_signature', :as => :new_signature
    post '/users/save_signature' => 'users#save_signature', :as => :save_signature
    match '/users/crop_signature' => 'users#crop_signature', :as => :crop_signature, via: :all

    get '/users/save_json_avatar' => 'users#save_json_avatar', :as => :save_json_avatar
    get '/users/new_avatar' => 'users#new_avatar', :as => :new_avatar
    post '/users/save_avatar' => 'users#save_avatar', :as => :save_avatar
    match '/users/crop_avatar' => 'users#crop_avatar', :as => :crop_avatar, via: :all

  resources :appraiser_steps
  resources :photos, :only => [:index, :create, :destroy]
  get '/photos/tag/:appraisal_id/:photo_id' => 'photos#tag', :as => :photo_tag
  post '/photos/set_as_default/:appraisal_id/:photo_id' => "photos#set_as_default", :as => :set_default_photo

  get '/appraisals/wizard_photo_upload/:appraisal_id' => 'appraisals#wizard_photo_upload', :as => :wizard_photo_upload, via: [:get]
  get '/appraisals/wizard_categories/:appraisal_id' => 'appraisals#wizard_categories', :as => :wizard_categories, via: [:get]
  match '/appraisals/share' => 'appraisals#share', :as => :share_appraisal, via: [:get, :post]
  get '/appraisals/show_shared/:id' => 'appraisals#show_shared', :as => :show_shared
  resources :appraisals do
    resources :build, controller: 'appraisals/build'
    resources :photos, :only => [:index, :create, :destroy]
    member do
      get 'reply'
      get 'claim'
    end
  end

  resource :appraiser , :controller => "appraiser" do
    resources :skills
  end

  get '/appraisers/submit_application' => 'appraiser#submit_application', :as => :submit_application
  get '/appraisers/get_application_status/:id' => "appraiser#get_application_status", :as => :get_application_status
  match '/appraisers/notify' => "appraiser#notify", :as => :appraisers_notify, via: [:get, :post]

  get '/skills/getRootCategories' => 'skills#getRootCategories'
  resources :classifications
  resources :skills, only: [:index, :create, :destroy]

  get 'contact' => 'contact#new', :as => 'contact'
  post 'contact' => 'contact#create'
  get 'complaint' => 'contact#complaint', :as => 'complaints', :via => :get
  get 'tickets' => 'contact#tickets', :as => :tickets
  get 'ticket' => 'contact#ticket', :as => :new_ticket
  post 'ticket' => 'contact#ticket_create', :as => :ticket_create
  get '/tickets/:id' => "contact#show", :as => :show_ticket

  # Static pages linked from CMS
  get 'unsubscribe' => 'home#unsubscribe'
  get '/home/how' => 'home#how', :as => 'how'
  get '/home/become' => 'home#become', :as => 'become'
  get '/home/privacy' => 'home#privacy', :as => 'privacy'
  get '/home/terms' => 'home#terms', :as => 'terms'
  get '/home/ethics' => 'home#ethics', :as => 'ethics'
  get '/home/determining' => 'home#determining', :as => 'determining'
  get '/home/limiting' => 'home#limiting', :as => 'limiting'
  get '/home/what_makes' => 'home#what_makes', :as => 'what_makes'
  get '/home/cost' => 'home#cost', :as => 'cost'
  get '/home/appraiser_invite' => 'home#appraiser_invite'
  get '/home/fee_schedule' => 'home#fee_schedule'
  get '/home/uspap_compliance' => 'home#uspap_compliance'
  get '/home/appraisal_body_restricteduse_USPAP_compliant_no' => 'home#appraisal_body_restricteduse_USPAP_compliant_no'
  get '/home/appraisal_body_restricteduse_USPAP_compliant_yes' => 'home#appraisal_body_restricteduse_USPAP_compliant_yes'
  get '/home/appraisal_body_summary_forselling_USPAP_compliant_no' => 'home#appraisal_body_summary_forselling_USPAP_compliant_no'
  get '/home/appraisal_body_summary_forselling_USPAP_compliant_yes' => 'home#appraisal_body_summary_forselling_USPAP_compliant_yes'
  get '/home/cost' => 'home#cost'
  get '/home/testimonials' => 'home#testimonials'
  get '/home/stores' => 'home#stores'
  get '/home/roadshows' => 'home#roadshows'
  get '/home/salvages' => 'home#salvages'
  get '/home/rare_books' => 'home#rare_books'
  get '/home/sports_memorabilia' => 'home#sports_memorabilia'
  get '/home/affiliate' => 'home#affiliate', :as => 'affiliate'
  get '/home/appraisal_provider_agreement' => 'home#appraisal_provider_agreement', :as => "appraisal_provider_agreement"
  get '/home/using_online_appraisals' => 'home#using_online_appraisals', :as => "using_online_appraisals"
  get '/home/cost_of_appraisals' => 'home#cost_of_appraisals', :as => "cost_of_appraisals"

  post '/appraisals/comment' => "appraisals#comment", :as => :comments
  get '/appraisals/reject/:id' => "appraisals#reject", :as => :appraisal_reject, via: [:all]
  get 'switch_user' => 'switch_user#set_current_user', via: [:all]
  ActiveAdmin.routes(self)

  get '/cms/blog/posts/:slug' => 'home#blog_redirect'
  get '/cms/blog' => 'home#blog_redirect'

  comfy_route :cms_admin, :path => '/admin'

  # Make sure this routeset is defined last
  comfy_route :cms, :path => '/', :sitemap => false
end

app/controllers/dashboard_controller.rb
class DashboardController < ApplicationController
	before_filter :authenticate_user!
	def index
		@user = current_user
		if @user.is_customer?
			redirect_to users_url
		elsif @user.is_appraiser? and !@user.is_confirmed?
			redirect_to appraiser_steps_path
		else

			case @detail = params[:detail]
				when "processing"
					@appraisals = Appraisal.where("assigned_to = ? and status = ?",current_user,EActivityValueClaimed).order("updated_at desc")
				when "unclaimed"
          @appraisals = Appraisal.where('(status = ? AND assigned_to IS null) OR (status = ? AND assigned_to = ?)', EActivityValuePayed, EActivityValuePayed, current_user.id)
          if Setting.is_set("show_all_appraisals","false")
            @specializedAppraisals = Appraisal.select("appraisals.id").joins(:classification => {:category => {:skills => :appraiser}}).where('appraisals.status in (?) and categories.id in (?)', [EActivityValuePayed, EActivityValueFinalized,EActivityValueClaimed ],current_user.skills.pluck(:category_id).uniq).pluck('appraisals.id').uniq
            @appraisals = @appraisals.where("id in (?)",@specializedAppraisals).order("updated_at desc")
          end
				when "referrals"
					@appraisals = Appraisal.where("appraiser_referral = ? and status = ?",current_user.referral_id,EActivityValuePayed).order("updated_at desc")
				when "completed"
					@appraisals = Appraisal.where("assigned_to = ? and status = ?",current_user,EActivityValueFinalized).order("updated_at desc")
        else
          # For unclaimed status
          @appraisals = Appraisal.where('(status = ? AND assigned_to IS null) OR (status = ? AND assigned_to = ?)', EActivityValuePayed, EActivityValuePayed, current_user.id).order("updated_at desc")

          # For all status
					# @appraisals = Appraisal.where("(status = ? AND assigned_to IS null) OR (assigned_to = ? )", EActivityValuePayed, current_user.id)
          
          if Setting.is_set("show_all_appraisals","false")
            @specializedAppraisals = Appraisal.select("appraisals.id").joins(:classification => {:category => {:skills => :appraiser}}).where('appraisals.status in (?) and categories.id in (?)', [EActivityValuePayed, EActivityValueFinalized,EActivityValueClaimed ],current_user.skills.pluck(:category_id).uniq).pluck('appraisals.id').uniq
            @appraisals = @appraisals.where("id in (?)",@specializedAppraisals)
          end

				end
			@appraisals = @appraisals.visible	unless @appraisals.nil?

			respond_to do |format|
				format.html # index.html.haml
				format.xml  { render :xml => @appraisals }
			end
		end
	end

	def payouts
		@payouts = Payout.joins(:appraisal).where("appraisals.assigned_to = ?",current_user).order(:created_at)

		case params[:status]
		when 'pending'
			@payouts = @payouts.where("payouts.created_at > ?", Time.now.beginning_of_month)
    when 'previous'
      @payouts = @payouts.where("payouts.created_at > ? and payouts.created_at <= ?", Time.now.beginning_of_month - 1.month, Time.now.beginning_of_month)
		when 'history'
			@payouts
		end
	end
end

app/controllers/users/admin/dashboard_controller.rb
class Users::Admin::DashboardController < ApplicationController
  before_filter :check_admin
  def show
    @appraiser_access_token = AppraiserAccessToken.new
  end

  def appraisers_index
    @users = User.where("role = 'appraiser'").paginate(:page => params[:page], :per_page => params[:per_page] || 100, :order => "created_at DESC")
  end

  def appraisers_invite_index
    @appraiser_access_tokens = AppraiserAccessToken.paginate(:page => params[:page], :per_page => params[:per_page] || 100, :order => "created_at DESC")
  end
end

app/helpers/dashboard_helper.rb
module DashboardHelper
end

app/views/dashboard/_appraiser_dashboard_navtabs.html.erb
<div class="row">
  <ul class="nav nav-tabs"> 
    <li class="dropdown <%= !@appraisals.nil? ? "active" : "" %>">
    <a href="#" data-toggle="dropdown" class="dropdown-toggle">Appraisals<b class="caret"></b></a>
    <ul class="dropdown-menu">
      <li><%= link_to 'Unclaimed Appraisals', dashboard_detail_path(:detail => 'unclaimed') %></li>
      <li><%= link_to 'My Referrals', dashboard_detail_path(:detail => 'referrals') %></li>
      <li><%= link_to 'Appraisals in Process', dashboard_detail_path(:detail => 'processing') %></li>
      <li><%= link_to 'My Completed Appraisals', dashboard_detail_path(:detail => 'completed') %></li>
    </ul>
    </li>
    <li class='dropdown <%= !@payouts.nil? ? "active" : "" %>"'>
    <a href="#" data-toggle="dropdown" class="dropdown-toggle">Transactions<b class="caret"></b></a>
    <ul class="dropdown-menu">
      <li><%= link_to 'Transactions This Month', dashboard_payouts_path(:status => 'pending') %></li>
      <li><%= link_to 'Transactions Previous Month', dashboard_payouts_path(:status => 'previous') %></li>
      <li><%= link_to 'Payment History', dashboard_payouts_path(:status => 'history') %></li>
    </ul>
    </li>
  </ul>
</div>

app/views/dashboard/_payout_table.html.erb
<div class="row">
  <div class="col-md-12">
    <% if payouts.empty? %>
      <h3>There are currently no transactions that match the selected conditions.</h3>
    <% else %>
      <table class="table table-striped table-condensed table-responsive">
        <thead>
          <tr>
            <th>Id</th>
            <th>Appraisal</th>
            <th>Completed On</th>
            <th>Plan</th>
            <th>Amount</th>
            <th>Status</th>
          </tr>
        </thead>
        <tbody>
          <% payouts.each do |payout| %>
            <tr>
              <td><%= payout.created_at.to_i %></td>
              <td><%= link_to(h(payout.appraisal.title) + " ##{payout.appraisal.id}", payout.appraisal)%></td>
              <td><%= payout.created_at %></td>
              <td><%= getStringForAppraisalType(payout.appraisal.selected_plan) %></td>
              <td><%= "#{print_amount_paid(payout.appraisal)}"%></td>
              <td><%= "#{print_payout_status(payout.appraisal)}" %></td>
            </tr>
          <% end %>
        </tbody>
      </table>
    <% end %>
  </div>
</div>

app/views/dashboard/index.html.erb
<div class="container">
  <%= render :partial => "appraiser_dashboard_navtabs" %>
  <%= render :partial => "/appraisals/appraisal_table", :locals => {:appraisals => @appraisals}%> 
</div>

app/views/dashboard/payouts.html.erb
<div class="container">
  <%= render :partial => "appraiser_dashboard_navtabs" %>
  <%= render :partial => "payout_table", :locals => {:payouts => @payouts} %>
</div>