config/routes.rb
PurexNew::Application.routes.draw do


  root :to => 'home#index'
  get "taxes/irs_income" => "taxes#irs_income", as: :taxes_income

  get "payouts/create"

  get "dashboard/payouts(/:status)" => "dashboard#payouts", :as => :dashboard_payouts
  get "dashboard(/:detail)" => 'dashboard#index', :as => :dashboard_detail

  post "tags/create" => "tags#create", :as => :annotate
  match "tags/destroy" => "tags#destroy", :as => :destroy_tag, via: [:get, :delete, :post]

  resources :payments, :only => [:create]
  get "/validate_coupon" => "payments#validate_coupon", :as => :validate_coupon, via: [:get]
  get "appraisal_data/create"
  get '/facebook/' => "users#facebook_login", via: [:get]
  match '/users/update_appraiser_status' => "users#update_appraiser_status", :as => :update_appraiser_status, via: [:post, :put]
  get '/users/get_user_by_vendor_token' => 'users#get_user_by_vendor_token'

  devise_for :users, :controllers => { :registrations => "registrations"}

  devise_for :appraisers, :controllers => { :registrations => "registrations"}

  devise_for :customers, :controllers => {:omniauth_callbacks => "omniauth_callbacks",  :registrations => "registrations"}

  match '/users/:id/finish_signup' => 'users#finish_signup', via: [:get, :patch], :as => :finish_signup

    post '/users/save_json_signature' => 'users#save_json_signature', :as => :save_json_signature
    get '/users/new_signature' => 'users#new_signature', :as => :new_signature
    post '/users/save_signature' => 'users#save_signature', :as => :save_signature
    match '/users/crop_signature' => 'users#crop_signature', :as => :crop_signature, via: :all

    get '/users/save_json_avatar' => 'users#save_json_avatar', :as => :save_json_avatar
    get '/users/new_avatar' => 'users#new_avatar', :as => :new_avatar
    post '/users/save_avatar' => 'users#save_avatar', :as => :save_avatar
    match '/users/crop_avatar' => 'users#crop_avatar', :as => :crop_avatar, via: :all

  resources :appraiser_steps
  resources :photos, :only => [:index, :create, :destroy]
  get '/photos/tag/:appraisal_id/:photo_id' => 'photos#tag', :as => :photo_tag
  post '/photos/set_as_default/:appraisal_id/:photo_id' => "photos#set_as_default", :as => :set_default_photo

  get '/appraisals/wizard_photo_upload/:appraisal_id' => 'appraisals#wizard_photo_upload', :as => :wizard_photo_upload, via: [:get]
  get '/appraisals/wizard_categories/:appraisal_id' => 'appraisals#wizard_categories', :as => :wizard_categories, via: [:get]
  match '/appraisals/share' => 'appraisals#share', :as => :share_appraisal, via: [:get, :post]
  get '/appraisals/show_shared/:id' => 'appraisals#show_shared', :as => :show_shared
  resources :appraisals do
    resources :build, controller: 'appraisals/build'
    resources :photos, :only => [:index, :create, :destroy]
    member do
      get 'reply'
      get 'claim'
    end
  end

  resource :appraiser , :controller => "appraiser" do
    resources :skills
  end

  get '/appraisers/submit_application' => 'appraiser#submit_application', :as => :submit_application
  get '/appraisers/get_application_status/:id' => "appraiser#get_application_status", :as => :get_application_status
  match '/appraisers/notify' => "appraiser#notify", :as => :appraisers_notify, via: [:get, :post]

  get '/skills/getRootCategories' => 'skills#getRootCategories'
  resources :classifications
  resources :skills, only: [:index, :create, :destroy]

  get 'contact' => 'contact#new', :as => 'contact'
  post 'contact' => 'contact#create'
  get 'complaint' => 'contact#complaint', :as => 'complaints', :via => :get
  get 'tickets' => 'contact#tickets', :as => :tickets
  get 'ticket' => 'contact#ticket', :as => :new_ticket
  post 'ticket' => 'contact#ticket_create', :as => :ticket_create
  get '/tickets/:id' => "contact#show", :as => :show_ticket

  # Static pages linked from CMS
  get 'unsubscribe' => 'home#unsubscribe'
  get '/home/how' => 'home#how', :as => 'how'
  get '/home/become' => 'home#become', :as => 'become'
  get '/home/privacy' => 'home#privacy', :as => 'privacy'
  get '/home/terms' => 'home#terms', :as => 'terms'
  get '/home/ethics' => 'home#ethics', :as => 'ethics'
  get '/home/determining' => 'home#determining', :as => 'determining'
  get '/home/limiting' => 'home#limiting', :as => 'limiting'
  get '/home/what_makes' => 'home#what_makes', :as => 'what_makes'
  get '/home/cost' => 'home#cost', :as => 'cost'
  get '/home/appraiser_invite' => 'home#appraiser_invite'
  get '/home/fee_schedule' => 'home#fee_schedule'
  get '/home/uspap_compliance' => 'home#uspap_compliance'
  get '/home/appraisal_body_restricteduse_USPAP_compliant_no' => 'home#appraisal_body_restricteduse_USPAP_compliant_no'
  get '/home/appraisal_body_restricteduse_USPAP_compliant_yes' => 'home#appraisal_body_restricteduse_USPAP_compliant_yes'
  get '/home/appraisal_body_summary_forselling_USPAP_compliant_no' => 'home#appraisal_body_summary_forselling_USPAP_compliant_no'
  get '/home/appraisal_body_summary_forselling_USPAP_compliant_yes' => 'home#appraisal_body_summary_forselling_USPAP_compliant_yes'
  get '/home/cost' => 'home#cost'
  get '/home/testimonials' => 'home#testimonials'
  get '/home/stores' => 'home#stores'
  get '/home/roadshows' => 'home#roadshows'
  get '/home/salvages' => 'home#salvages'
  get '/home/rare_books' => 'home#rare_books'
  get '/home/sports_memorabilia' => 'home#sports_memorabilia'
  get '/home/affiliate' => 'home#affiliate', :as => 'affiliate'
  get '/home/appraisal_provider_agreement' => 'home#appraisal_provider_agreement', :as => "appraisal_provider_agreement"
  get '/home/using_online_appraisals' => 'home#using_online_appraisals', :as => "using_online_appraisals"
  get '/home/cost_of_appraisals' => 'home#cost_of_appraisals', :as => "cost_of_appraisals"

  post '/appraisals/comment' => "appraisals#comment", :as => :comments
  get '/appraisals/reject/:id' => "appraisals#reject", :as => :appraisal_reject, via: [:all]
  get 'switch_user' => 'switch_user#set_current_user', via: [:all]
  ActiveAdmin.routes(self)

  get '/cms/blog/posts/:slug' => 'home#blog_redirect'
  get '/cms/blog' => 'home#blog_redirect'

  comfy_route :cms_admin, :path => '/admin'

  # Make sure this routeset is defined last
  comfy_route :cms, :path => '/', :sitemap => false
end

app/controllers/home_controller.rb
class HomeController < ApplicationController
  before_filter :authenticate_user!, :only => :fee_schedule

  # Home Page
  def index
    @user = User.new
    @featured_coupon = Coupon.get_featured
    flash.keep
    return redirect_to get_index_for_user_type(current_user) unless current_user.nil?
  end

  def unsubscribe
    token = params[:token]
    # decrypt token get user_id
    crypt = ActiveSupport::MessageEncryptor.new(Devise.secret_key)
    user_id = crypt.decrypt_and_verify(token)
    user =  User.find(user_id) rescue nil
    if user
      user.is_deny_email = true
      user.save
      redirect_to(root_path, :notice => ' You have successfully unsubscribed from our reminder for your uncompleted appraisal.')
    else
      render :file => "#{Rails.root}/public/422.html", :status => 422, :layout => false
    end
  end

  # Terms and Conditions
  def terms
    respond_to do |format|
      format.html
      format.pdf do
        render :pdf => "terms_of_service"
      end
    end
  end

  # Privacy Policy
  def privacy
    render cms_page: '/privacy-policy'
  end

  # How it works
  def how
    @role = params[:role]
  end

  # Become an Appraiser page
  def become
    render cms_page: '/become'
  end

  # Appraiser code of Ethics
  def ethics
    respond_to do |format|
      format.html
      format.pdf do
        render :pdf => "code_of_ethics"
      end
    end
  end

  # Determining Value
  def determining
    render cms_page: '/determining'
  end

  # Limiting Conditions and Extraordinary Assumptions
  def limiting
    render cms_page: '/limiting'
  end

  def what_makes
    render cms_page: '/what_makes'
  end

  def fee_schedule
    render cms_page: '/fee-schedule'
  end

  def uspap_compliance
    render cms_page: '/uspap-compliance'
  end

  # Examples of supplementary information
  def appraisal_body_restricteduse_USPAP_compliant_no
    render cms_page: '/appraisal-body-restricteduse-uspap-compliant-no'
  end

  def appraisal_body_restricteduse_USPAP_compliant_yes
    render cms_page: '/appraisal-body-restricteduse-uspap-compliant-yes'
  end

  def appraisal_body_summary_forselling_USPAP_compliant_no
    render cms_page: '/appraisal-body-summary-forselling-uspap-compliant-no'
  end

  def appraisal_body_summary_forselling_USPAP_compliant_yes
    render cms_page: '/appraisal-body-summary-forselling-uspap-compliant-yes'
  end

  def cost
    render cms_page: '/cost-of-appraisals'
  end

  def testimonials
  end

  def stores
  end

  def roadshows
  end

  def salvages
  end

  def rare_books
  end
  
  def sports_memorabilia
  end
  
  def affiliate
  end

  def appraisal_provider_agreement
    respond_to do |format|
      format.html
      format.pdf do
        render :pdf => "appraisal_provider_agreement"
      end
    end
  end

  def blog_redirect
    url = params[:slug] ? "http://blog.valuethisnow.com/posts/#{params[:slug]}" : "http://blog.valuethisnow.com"
    redirect_to url
  end

  def using_online_appraisals
    render cms_page: '/using-online-appraisals'
  end

  def cost_of_appraisals
    render cms_page: '/cost-of-appraisals'
  end


end

app/helpers/home_helper.rb
module HomeHelper
end

app/views/home/appraisal_provider_agreement.erb
<%= get_static_page_html('/appraisal-provider-agreement')%>

app/views/home/become.html.erb
<%= get_cms_content('/become') %>

app/views/home/ethics.erb
<%= get_cms_content('/ethics') %>

app/views/home/how.html.erb
<div class="row">
  <div class="col-md-9 col-md-offset-1">
    <% if @role == "consumer" %>
      <%= get_cms_content('/how-it-works-consumers') %>
    <% elsif @role == "appraiser" %>
      <%= get_cms_content('/how-it-works-appraisers') %>
    <% else %>
      <div class="row">
        <div class="col-md-5 col-md-offset-2">
          <%= link_to 'For Consumers', how_path(:role => "consumer"), :class => "btn btn-success btn-large" %>
        </div>
        <div class="col-md-5">
          <%= link_to 'For Appraisers', how_path(:role => "appraiser"), :class => "btn btn-success btn-large" %>
        </div>
      </div>
    <% end %>
  </div>
</div>

app/views/home/index.html.erb
<div id="home">
  <div class="row hidden-xs" id="main-block">
    <div class="col-md-12">
      <div class="row">
        <div class="col-md-12">
          <div class="title ">
            Online appraisals made easy
          </div>
          <div class="sign-in">
            <%= link_to "Sign in / Sign up to get an appraisal", main_app.new_user_session_path, class: "big-button yellow-button" %>
          </div>
        </div>
      </div>

      <div class="row">
        <div class="col-md-6 hidden-xs">
          <div id="homeVideo" class="responsive-container">
            <object class="frame" type="application/x-shockwave-flash" style="width:538px; height:302px;" data="https://www.youtube.com/v/5q8XwHpGMZY?color2=FBE9EC&amp;version=3">
              <param name="movie" value="https://www.youtube.com/v/5q8XwHpGMZY?color2=FBE9EC&amp;version=3" />
              <param name="allowFullScreen" value="true" />
              <param name="allowscriptaccess" value="always" />
            </object>
          </div>
        </div>
        <div class="col-md-6 visible-lg">
          <div class="featured-item">
            <div id="homeItem"> 
            </div>
            <div id="homeValueBlock">
              <div id="theTitle">
              </div>
              <%= link_to "What's your item worth?", main_app.new_user_session_path %>
            </div>

            <div id="homeSocial">
              <a href="http://www.facebook.com/ValueThisNow" title="Visit our Facebook page."><span id="hS1"></span></a>
              <a href="http://www.twitter.com/valuethisnow" title="See our twitter feed."><span id="hS2"></span></a>
              <a href="http://pinterest.com/valuethisnow" title="See our Pinterest board."><span id="hS3"></span></a>
            </div>
          </div>
        </div>
      </div>
    </div>
  </div>
  <div class="row visible-xs" id="main-block-xs">
    <div class="col-md-2">
          <div class="title text-center">
            Online appraisals made easy
          </div>
          <div class="sign-in text-center">
            <%= link_to "Sign in / Sign up to get an appraisal", main_app.new_user_session_path, class: "yellow-button" %>
          </div>
    </div>
  
  </div>
  <!-- Home block 1 -->
  <div class="row" id="featured-coupon-block">
    <!-- <div class="col-md-12"> -->
      <%= render partial: 'layouts/featured_coupon'  %>
    <!-- </div> -->
  </div>
  <!-- Middle 2 -->
  <div class="row" id="mid-block">
    <div class="visible-lg visible-md">
    <%= render partial: "layouts/livehelpnow" %>
    </div>
    <div class="row">
      <div class="col-md-9 col-md-offset-1">
        <div class="row">
          <div class="col-md-12 detail">
            <div class="title">
              <%= image_tag "m1.jpg" %>
              Tell us about your item online 
            </div>
            <div class="copy">
              Fill out our appraisal form and let us know as much information about the item as you have. One or more digital photos of your item is all you need.
            </div>
          </div>
        </div>
        <div class="row">
          <div class="col-md-12 detail">
            <div class="title">
              <%= image_tag "m2.jpg" %>
              Our experts will appraise it. It's that simple!
            </div>
            <div class="copy">
              You will receive a professional appraisal of your item which will help you see its true value
            </div>
            <div class="copy">
              <%= link_to 'Learn more about online appraisals.', how_path(role: 'consumer') %>
            </div>
            <div class="sign-in" >
              <%= link_to "Sign in / Sign up to get an appraisal", main_app.new_user_session_path, class: "yellow-button" %>
            </div>

          </div>
        </div>
      </div>
    </div>
  </div>
  <!-- Middle 3 -->
  <div class="row" id="mid-block-2">
    <div class="col-md-9 col-md-offset-1">
      <div class="row">
        <div class="col-md-12">
          <div class="title">
            Appraisals give you more than just a value
          </div>
        </div>
      </div>
      <div class="row">
        <div class="col-md-8">
          <div class="copy">
            <%= get_cms_content('/index-block-1') %>
          </div>
        </div>
        <div class="col-md-4">
          <%= image_tag("h_items.png", class: "img-responsive") %>
        </div>
      </div>
    </div>
  </div>
  <!-- Middle 4 -->
  <div class="row" id="bottom-block">
    <div class="col-md-9 col-md-offset-1">
      <div class="row">
        <div class="col-md-4">
              <img id="Image-Maps_1201309101116038" src="<%= image_path("h_logos.png") %>" usemap="#Image-Maps_1201309101116038" border="0" width="200" height="121" alt=""/>
              <map id="_Image-Maps_1201309101116038" name="Image-Maps_1201309101116038">
                <area shape="poly" coords="0,69,79,71,81,112,0,109," href="http://en.wikipedia.org/wiki/Uniform_Standards_of_Professional_Appraisal_Practice" alt="USPAP" title="USPAP"   />
                <area shape="poly" coords="127,63,197,67,198,106,123,106," href="http://www.aoaonline.org" alt="Association of Online Appraisers" title="Association of Online Appraisers" />
              </map>
        </div>
        <div class="col-md-8">
          <div class="title">
            The Value This Now Advantage
          </div>
          <div class="copy">
            <%= get_cms_content('/index-block-2') %>
          </div>
        </div>
      </div>
    </div>
  </div>
</div>

app/views/home/privacy.html.erb
<%= get_cms_content('/privacy') %>

app/views/home/rare-books.html.erb
<%= get_static_page_html2('/rare-books') %>

app/views/home/rare_books.html.erb
<%= get_static_page_html2('/rare-books') %>

app/views/home/roadshows.html.erb
<%= get_static_page_html2('/roadshow') %>

app/views/home/salvages.html.erb
<%= get_static_page_html2('/salvage') %>

app/views/home/sports_memorabilia.html.erb
<%= get_static_page_html2('/sports-memorabilia') %>

app/views/home/stores.html.erb
<%= get_static_page_html2('/store') %>

app/views/home/terms.erb
<%= get_cms_content('/terms-and-conditions') %>

app/views/home/testimonials.html.erb
<%= get_static_page_html('/testimonials') %>