config/routes.rb
PurexNew::Application.routes.draw do


  root :to => 'home#index'
  get "taxes/irs_income" => "taxes#irs_income", as: :taxes_income

  get "payouts/create"

  get "dashboard/payouts(/:status)" => "dashboard#payouts", :as => :dashboard_payouts
  get "dashboard(/:detail)" => 'dashboard#index', :as => :dashboard_detail

  post "tags/create" => "tags#create", :as => :annotate
  match "tags/destroy" => "tags#destroy", :as => :destroy_tag, via: [:get, :delete, :post]

  resources :payments, :only => [:create]
  get "/validate_coupon" => "payments#validate_coupon", :as => :validate_coupon, via: [:get]
  get "appraisal_data/create"
  get '/facebook/' => "users#facebook_login", via: [:get]
  match '/users/update_appraiser_status' => "users#update_appraiser_status", :as => :update_appraiser_status, via: [:post, :put]
  get '/users/get_user_by_vendor_token' => 'users#get_user_by_vendor_token'

  devise_for :users, :controllers => { :registrations => "registrations"}

  devise_for :appraisers, :controllers => { :registrations => "registrations"}

  devise_for :customers, :controllers => {:omniauth_callbacks => "omniauth_callbacks",  :registrations => "registrations"}

  match '/users/:id/finish_signup' => 'users#finish_signup', via: [:get, :patch], :as => :finish_signup

    post '/users/save_json_signature' => 'users#save_json_signature', :as => :save_json_signature
    get '/users/new_signature' => 'users#new_signature', :as => :new_signature
    post '/users/save_signature' => 'users#save_signature', :as => :save_signature
    match '/users/crop_signature' => 'users#crop_signature', :as => :crop_signature, via: :all

    get '/users/save_json_avatar' => 'users#save_json_avatar', :as => :save_json_avatar
    get '/users/new_avatar' => 'users#new_avatar', :as => :new_avatar
    post '/users/save_avatar' => 'users#save_avatar', :as => :save_avatar
    match '/users/crop_avatar' => 'users#crop_avatar', :as => :crop_avatar, via: :all

  resources :appraiser_steps
  resources :photos, :only => [:index, :create, :destroy]
  get '/photos/tag/:appraisal_id/:photo_id' => 'photos#tag', :as => :photo_tag
  post '/photos/set_as_default/:appraisal_id/:photo_id' => "photos#set_as_default", :as => :set_default_photo

  get '/appraisals/wizard_photo_upload/:appraisal_id' => 'appraisals#wizard_photo_upload', :as => :wizard_photo_upload, via: [:get]
  get '/appraisals/wizard_categories/:appraisal_id' => 'appraisals#wizard_categories', :as => :wizard_categories, via: [:get]
  match '/appraisals/share' => 'appraisals#share', :as => :share_appraisal, via: [:get, :post]
  get '/appraisals/show_shared/:id' => 'appraisals#show_shared', :as => :show_shared
  resources :appraisals do
    resources :build, controller: 'appraisals/build'
    resources :photos, :only => [:index, :create, :destroy]
    member do
      get 'reply'
      get 'claim'
    end
  end

  resource :appraiser , :controller => "appraiser" do
    resources :skills
  end

  get '/appraisers/submit_application' => 'appraiser#submit_application', :as => :submit_application
  get '/appraisers/get_application_status/:id' => "appraiser#get_application_status", :as => :get_application_status
  match '/appraisers/notify' => "appraiser#notify", :as => :appraisers_notify, via: [:get, :post]

  get '/skills/getRootCategories' => 'skills#getRootCategories'
  resources :classifications
  resources :skills, only: [:index, :create, :destroy]

  get 'contact' => 'contact#new', :as => 'contact'
  post 'contact' => 'contact#create'
  get 'complaint' => 'contact#complaint', :as => 'complaints', :via => :get
  get 'tickets' => 'contact#tickets', :as => :tickets
  get 'ticket' => 'contact#ticket', :as => :new_ticket
  post 'ticket' => 'contact#ticket_create', :as => :ticket_create
  get '/tickets/:id' => "contact#show", :as => :show_ticket

  # Static pages linked from CMS
  get 'unsubscribe' => 'home#unsubscribe'
  get '/home/how' => 'home#how', :as => 'how'
  get '/home/become' => 'home#become', :as => 'become'
  get '/home/privacy' => 'home#privacy', :as => 'privacy'
  get '/home/terms' => 'home#terms', :as => 'terms'
  get '/home/ethics' => 'home#ethics', :as => 'ethics'
  get '/home/determining' => 'home#determining', :as => 'determining'
  get '/home/limiting' => 'home#limiting', :as => 'limiting'
  get '/home/what_makes' => 'home#what_makes', :as => 'what_makes'
  get '/home/cost' => 'home#cost', :as => 'cost'
  get '/home/appraiser_invite' => 'home#appraiser_invite'
  get '/home/fee_schedule' => 'home#fee_schedule'
  get '/home/uspap_compliance' => 'home#uspap_compliance'
  get '/home/appraisal_body_restricteduse_USPAP_compliant_no' => 'home#appraisal_body_restricteduse_USPAP_compliant_no'
  get '/home/appraisal_body_restricteduse_USPAP_compliant_yes' => 'home#appraisal_body_restricteduse_USPAP_compliant_yes'
  get '/home/appraisal_body_summary_forselling_USPAP_compliant_no' => 'home#appraisal_body_summary_forselling_USPAP_compliant_no'
  get '/home/appraisal_body_summary_forselling_USPAP_compliant_yes' => 'home#appraisal_body_summary_forselling_USPAP_compliant_yes'
  get '/home/cost' => 'home#cost'
  get '/home/testimonials' => 'home#testimonials'
  get '/home/stores' => 'home#stores'
  get '/home/roadshows' => 'home#roadshows'
  get '/home/salvages' => 'home#salvages'
  get '/home/rare_books' => 'home#rare_books'
  get '/home/sports_memorabilia' => 'home#sports_memorabilia'
  get '/home/affiliate' => 'home#affiliate', :as => 'affiliate'
  get '/home/appraisal_provider_agreement' => 'home#appraisal_provider_agreement', :as => "appraisal_provider_agreement"
  get '/home/using_online_appraisals' => 'home#using_online_appraisals', :as => "using_online_appraisals"
  get '/home/cost_of_appraisals' => 'home#cost_of_appraisals', :as => "cost_of_appraisals"

  post '/appraisals/comment' => "appraisals#comment", :as => :comments
  get '/appraisals/reject/:id' => "appraisals#reject", :as => :appraisal_reject, via: [:all]
  get 'switch_user' => 'switch_user#set_current_user', via: [:all]
  ActiveAdmin.routes(self)

  get '/cms/blog/posts/:slug' => 'home#blog_redirect'
  get '/cms/blog' => 'home#blog_redirect'

  comfy_route :cms_admin, :path => '/admin'

  # Make sure this routeset is defined last
  comfy_route :cms, :path => '/', :sitemap => false
end

app/controllers/appraisals/build_controller.rb
class Appraisals::BuildController < ApplicationController
  include Wicked::Wizard

  steps :general, :characteristics, :photos, :plan, :payment, :thank

  def show
    @appraisal = Appraisal.find(params[:appraisal_id])
    @photos = @appraisal.photos
    @appraisal.payment = Payment.new(user_id: current_user.id, appraisal_id: @appraisal.id) if @appraisal.payment.nil?
    render_wizard
  end

  def create
    @appraisal = Appraisal.create(created_by: current_user.id, status: EActivityValueCreated)
    redirect_to wizard_path(steps.first, :appraisal_id => @appraisal.id)
  end

  def update
    @appraisal = Appraisal.find(params[:appraisal_id])
    params[:appraisal][:appraisal_info] = @appraisal.merge_appraisal_info(params)
    params[:appraisal].except!(:payment_attributes)
    params[:appraisal][:step] = step
    params[:appraisal][:step] = 'active' if step == steps.last
    params[:appraisal][:selected_plan] = (params[:appraisal][:selected_plan].to_i + 4) if params[:isPair]
    @appraisal.update_attributes(params[:appraisal])
    @appraisal.assigned_to = Appraiser.find(@appraisal.appraiser_referral.to_i) unless @appraisal.appraiser_referral.eql?("") 
    @appraisal.save
    render_wizard @appraisal
  end
end

app/helpers/appraisals_helper.rb
module AppraisalsHelper

  def print_replacement_cost(appraisal)
    return "-" if (appraisal.status != EActivityValueFinalized && appraisal.status != EActivityValueClaimed)
    unless (appraisal.appraisal_info.replacement_cost_min.blank? || appraisal.appraisal_info.replacement_cost_max.blank?)
      "#{print_as_currency(appraisal.appraisal_info.replacement_cost_min)} to #{print_as_currency(appraisal.appraisal_info.replacement_cost_max)} " 
    end
  end

  def print_fair_market_value(appraisal)
    return "-" if (appraisal.status != EActivityValueFinalized && appraisal.status != EActivityValueClaimed)
    unless (appraisal.appraisal_info.fair_market_value_min.blank? || appraisal.appraisal_info.fair_market_value_max.blank?)
      "#{print_as_currency(appraisal.appraisal_info.fair_market_value_min)} to #{print_as_currency(appraisal.appraisal_info.fair_market_value_max)}"
    end
  end

  def print_amount_paid(appraisal)
    if appraisal.status == EActivityValueFinalized && !appraisal.payout.nil?
      "#{print_as_currency(appraisal.payout.amount)}"
    end
  end

  def print_payout_status(appraisal)
    if appraisal.status == EActivityValueFinalized && !appraisal.payout.nil?
      "#{getStringForPayoutStatus(appraisal.payout.status)}"
    end
  end

  def linked_thumbnail(appraisal)
    link_to image_tag(appraisal.default_photo.picture_url(:thumb), :class => "tagThumb"), _get_linked_path(appraisal), :title => h(appraisal.title) unless appraisal.photos.count == 0
  end

  def linked_title(appraisal)
    badge = "<span class='label'><i class='icon-lock icon-white'></i></span>" unless appraisal.appraiser_referral.blank?
    link_to(raw(badge) + h(appraisal.title) + " ##{appraisal.id}", _get_linked_path(appraisal))
  end

  def completed_on(appraisal)
    return "-" if appraisal.status != EActivityValueFinalized
    distance_of_time_in_words(Time.now,appraisal.updated_at) + " ago"
  end

  def appraisal_buttons(appraisal, role = 'appraiser', small = false)
    if role == "appraiser"
      if small
        case appraisal.status
        when EActivityValueClaimed
          link_to reply_appraisal_path(appraisal), :class => "btn btn-success btn-xs" do raw('<span class="glyphicon glyphicon-edit"></spani>') end
        when EActivityValuePayed
          link_to appraisal, :class => "btn btn-success btn-xs" do raw('<span class="glyphicon glyphicon-folder-open"></span>') end
        when EActivityValueFinalized
          link_to show_shared_path(appraisal, :format => :pdf), :class => "btn btn-success btn-xs" do raw('<span class="glyphicon glyphicon-download-alt"></i>') end
        end
      else
        case appraisal.status
        when EActivityValueClaimed
          link_to reply_appraisal_path(appraisal), :class => "btn btn-success btn-sm" do raw('<span class="glyphicon glyphicon-edit"></span> Reply') end
        when EActivityValuePayed
          link_to appraisal, :class => "btn btn-success btn-sm" do raw('<span class="glyphicon glyphicon-folder-open"></span> View') end
        when EActivityValueFinalized
          link_to "Download PDF", show_shared_path(appraisal, :format => :pdf), :class => "btn btn-success btn-sm" 
        end
      end
    end
  end

  private
  def _get_linked_path(appraisal)
    return appraisal.status == EActivityValueCreated ? appraisal_build_index_path(appraisal) : appraisal
  end


end

app/views/appraisals/partials/_appraisal_table_for_users.html.erb
<table class="table table-striped table-condensed table-responsive ">
  <thead>
    <tr>
      <th class="hidden-xs">Item</th>
      <th>Item #</th>
      <th>Status</th>
      <th>Date Appraised</th>
      <th class="hidden-xs">Estimated<br>Retail Value</th>
      <th class="hidden-xs">Estimated<br>Replacement Value</th>
      <th class="hidden-xs">Appraisal Type</th>
      <th></th>
      <th></th>
    </tr>
  </thead>
  <tbody>
    <% appraisals.each do |appraisal| %>
      <tr>
        <td class="hidden-xs"><%= linked_thumbnail(appraisal) %></td>
        <td><%= linked_title(appraisal) %></td>
        <td><%= getStringForActivityValue(appraisal.status) %></td>
        <td><%= completed_on(appraisal) %></td>
        <td class="hidden-xs"><%= print_fair_market_value(appraisal) %></td>
        <td class="hidden-xs"><%= print_replacement_cost(appraisal) %></td>
        <td class="hidden-xs"><%= getStringForAppraisalType(appraisal.selected_plan) %></td>
        <td>
          <div class="hidden-xs hidden-sm">
            <%= link_to('Edit', appraisal_build_index_path(appraisal), :class => "btn btn-success btn-sm", :style => "margin:2px;") if appraisal.status == EActivityValueCreated %>
            <%= link_to('Edit', edit_appraisal_path(appraisal), :class => "btn btn-success btn-sm", :style => "margin:2px;") if appraisal.status == EActivityValuePayed %>
            <%= link_to show_shared_path(appraisal, :format => :pdf), :class => "btn btn-success btn-sm" do %>Download PDF<% end if appraisal.status == EActivityValueFinalized%>
          </div>
          <div class="visible-xs visible-sm">
            <%= link_to appraisal_build_index_path(appraisal), :class => "btn btn-success btn-xs" do %><span class="glyphicon glyphicon-pencil"></span> <% end if appraisal.status == EActivityValueCreated %>
            <%= link_to edit_appraisal_path(appraisal), :class => "btn btn-success btn-xs" do %><span class="glyphicon glyphicon-pencil"></span> <% end if appraisal.status == EActivityValuePayed %>
            <%= link_to show_shared_path(appraisal, :format => :pdf), :class => "btn btn-success btn-xs" do %><span class="glyphicon glyphicon-download-alt"></span><% end if appraisal.status == EActivityValueFinalized%>
          </div>
        </td>
        <td>
          <div class="hidden-xs hidden-sm">
            <%= button_to('Delete', appraisal, :confirm => 'Are you sure?', :method => :delete, :class => "btn btn-success btn-sm") if appraisal.status == EActivityValueCreated %>
            <% if appraisal.status == EActivityValueFinalized %>
              <%= render :partial => "appraisals/partials/push_to_social", :locals => {:appraisal => appraisal} %>
            <% end %>
          </div>
          <div class="visible-xs visible-sm">
            <%= button_to appraisal, :confirm => 'Are you sure?', :method => :delete, :class => "btn btn-success btn-xs" do %><span class="glyphicon glyphicon-trash"></span><% end if appraisal.status == EActivityValueCreated %>
            <% if appraisal.status == EActivityValueFinalized %>
              <%= render :partial => "appraisals/partials/push_to_social", :locals => {:appraisal => appraisal} %>
            <% end %>
          </div>
        </td>
      </tr>
    <% end %>
  </tbody>
</table>

app/views/appraisals/partials/_push_to_social.html.erb
<div class="hidden-xs hidden-sm">
  <span class='st_sharethis_large' st_url="<%= get_url_for_shared_appraisal(appraisal) %>" st_title="Value This Now"></span>
</div>
<div class="visible-xs visible-sm">
  <span class='st_sharethis' st_url="<%= get_url_for_shared_appraisal(appraisal) %>" st_title="Value This Now"></span>
</div>