config/routes.rb
PurexNew::Application.routes.draw do


  root :to => 'home#index'
  get "taxes/irs_income" => "taxes#irs_income", as: :taxes_income

  get "payouts/create"

  get "dashboard/payouts(/:status)" => "dashboard#payouts", :as => :dashboard_payouts
  get "dashboard(/:detail)" => 'dashboard#index', :as => :dashboard_detail

  post "tags/create" => "tags#create", :as => :annotate
  match "tags/destroy" => "tags#destroy", :as => :destroy_tag, via: [:get, :delete, :post]

  resources :payments, :only => [:create]
  get "/validate_coupon" => "payments#validate_coupon", :as => :validate_coupon, via: [:get]
  get "appraisal_data/create"
  get '/facebook/' => "users#facebook_login", via: [:get]
  match '/users/update_appraiser_status' => "users#update_appraiser_status", :as => :update_appraiser_status, via: [:post, :put]
  get '/users/get_user_by_vendor_token' => 'users#get_user_by_vendor_token'

  devise_for :users, :controllers => { :registrations => "registrations"}

  devise_for :appraisers, :controllers => { :registrations => "registrations"}

  devise_for :customers, :controllers => {:omniauth_callbacks => "omniauth_callbacks",  :registrations => "registrations"}

  match '/users/:id/finish_signup' => 'users#finish_signup', via: [:get, :patch], :as => :finish_signup

    post '/users/save_json_signature' => 'users#save_json_signature', :as => :save_json_signature
    get '/users/new_signature' => 'users#new_signature', :as => :new_signature
    post '/users/save_signature' => 'users#save_signature', :as => :save_signature
    match '/users/crop_signature' => 'users#crop_signature', :as => :crop_signature, via: :all

    get '/users/save_json_avatar' => 'users#save_json_avatar', :as => :save_json_avatar
    get '/users/new_avatar' => 'users#new_avatar', :as => :new_avatar
    post '/users/save_avatar' => 'users#save_avatar', :as => :save_avatar
    match '/users/crop_avatar' => 'users#crop_avatar', :as => :crop_avatar, via: :all

  resources :appraiser_steps
  resources :photos, :only => [:index, :create, :destroy]
  get '/photos/tag/:appraisal_id/:photo_id' => 'photos#tag', :as => :photo_tag
  post '/photos/set_as_default/:appraisal_id/:photo_id' => "photos#set_as_default", :as => :set_default_photo

  get '/appraisals/wizard_photo_upload/:appraisal_id' => 'appraisals#wizard_photo_upload', :as => :wizard_photo_upload, via: [:get]
  get '/appraisals/wizard_categories/:appraisal_id' => 'appraisals#wizard_categories', :as => :wizard_categories, via: [:get]
  match '/appraisals/share' => 'appraisals#share', :as => :share_appraisal, via: [:get, :post]
  get '/appraisals/show_shared/:id' => 'appraisals#show_shared', :as => :show_shared
  resources :appraisals do
    resources :build, controller: 'appraisals/build'
    resources :photos, :only => [:index, :create, :destroy]
    member do
      get 'reply'
      get 'claim'
    end
  end

  resource :appraiser , :controller => "appraiser" do
    resources :skills
  end

  get '/appraisers/submit_application' => 'appraiser#submit_application', :as => :submit_application
  get '/appraisers/get_application_status/:id' => "appraiser#get_application_status", :as => :get_application_status
  match '/appraisers/notify' => "appraiser#notify", :as => :appraisers_notify, via: [:get, :post]

  get '/skills/getRootCategories' => 'skills#getRootCategories'
  resources :classifications
  resources :skills, only: [:index, :create, :destroy]

  get 'contact' => 'contact#new', :as => 'contact'
  post 'contact' => 'contact#create'
  get 'complaint' => 'contact#complaint', :as => 'complaints', :via => :get
  get 'tickets' => 'contact#tickets', :as => :tickets
  get 'ticket' => 'contact#ticket', :as => :new_ticket
  post 'ticket' => 'contact#ticket_create', :as => :ticket_create
  get '/tickets/:id' => "contact#show", :as => :show_ticket

  # Static pages linked from CMS
  get 'unsubscribe' => 'home#unsubscribe'
  get '/home/how' => 'home#how', :as => 'how'
  get '/home/become' => 'home#become', :as => 'become'
  get '/home/privacy' => 'home#privacy', :as => 'privacy'
  get '/home/terms' => 'home#terms', :as => 'terms'
  get '/home/ethics' => 'home#ethics', :as => 'ethics'
  get '/home/determining' => 'home#determining', :as => 'determining'
  get '/home/limiting' => 'home#limiting', :as => 'limiting'
  get '/home/what_makes' => 'home#what_makes', :as => 'what_makes'
  get '/home/cost' => 'home#cost', :as => 'cost'
  get '/home/appraiser_invite' => 'home#appraiser_invite'
  get '/home/fee_schedule' => 'home#fee_schedule'
  get '/home/uspap_compliance' => 'home#uspap_compliance'
  get '/home/appraisal_body_restricteduse_USPAP_compliant_no' => 'home#appraisal_body_restricteduse_USPAP_compliant_no'
  get '/home/appraisal_body_restricteduse_USPAP_compliant_yes' => 'home#appraisal_body_restricteduse_USPAP_compliant_yes'
  get '/home/appraisal_body_summary_forselling_USPAP_compliant_no' => 'home#appraisal_body_summary_forselling_USPAP_compliant_no'
  get '/home/appraisal_body_summary_forselling_USPAP_compliant_yes' => 'home#appraisal_body_summary_forselling_USPAP_compliant_yes'
  get '/home/cost' => 'home#cost'
  get '/home/testimonials' => 'home#testimonials'
  get '/home/stores' => 'home#stores'
  get '/home/roadshows' => 'home#roadshows'
  get '/home/salvages' => 'home#salvages'
  get '/home/rare_books' => 'home#rare_books'
  get '/home/sports_memorabilia' => 'home#sports_memorabilia'
  get '/home/affiliate' => 'home#affiliate', :as => 'affiliate'
  get '/home/appraisal_provider_agreement' => 'home#appraisal_provider_agreement', :as => "appraisal_provider_agreement"
  get '/home/using_online_appraisals' => 'home#using_online_appraisals', :as => "using_online_appraisals"
  get '/home/cost_of_appraisals' => 'home#cost_of_appraisals', :as => "cost_of_appraisals"

  post '/appraisals/comment' => "appraisals#comment", :as => :comments
  get '/appraisals/reject/:id' => "appraisals#reject", :as => :appraisal_reject, via: [:all]
  get 'switch_user' => 'switch_user#set_current_user', via: [:all]
  ActiveAdmin.routes(self)

  get '/cms/blog/posts/:slug' => 'home#blog_redirect'
  get '/cms/blog' => 'home#blog_redirect'

  comfy_route :cms_admin, :path => '/admin'

  # Make sure this routeset is defined last
  comfy_route :cms, :path => '/', :sitemap => false
end

app/controllers/contact_controller.rb
require 'complaints'
class ContactController < ApplicationController
	def new
		@message = Message.new
		@role = current_user.type.downcase if current_user
	end

	def create
		@message = Message.new(params[:message])

		if @message.valid?
      if !current_user
				mailer_method = "contact_us"
      elsif current_user.is_appraiser?
				mailer_method = "appraiser_support"
			elsif current_user.is_customer?
				mailer_method = "user_support"
			else
				mailer_method = "contact_us"
			end
			eval "UserMailer.#{mailer_method}(@message).deliver"
			redirect_to(root_path, :notice => "Thank you, your message was sent, someone should be in contact shortly.")
		else
      flash[:alert] = "Please fill all fields."
			render :new
		end
	end

	def complaint
		@user = current_user
		lighthouse = TaskMapper.new(TASK_MAPPER[Rails.env]['provider'], {:token => TASK_MAPPER[Rails.env]['token'], :account => TASK_MAPPER[Rails.env]['account']})
		project =  lighthouse.project.find(TASK_MAPPER[Rails.env]['project_id'])
	end

	def tickets
		@user = current_user
		@ticketConnector = Complaints::Lighthouse.new()
		@tickets = @user.nil? ? [] : current_user.tickets
	end

	def ticket
		@user = current_user
		@ticket = Ticket.new(:user_id => current_user.id)
		@appraisals = Appraisal.where("created_by =? or assigned_to = ? ",current_user, current_user).order("id ASC")
	end

	def ticket_create
		@user = current_user
		@ticketConnector = Complaints::Lighthouse.new()
		a = Appraisal.find(params[:ticket][:appraisal_id])
		body = "Appraisal: #{a.id}-#{a.title}\n"
		body += "User : #{current_user.id} #{current_user.name} #{current_user.email}\n"
		body += "Comments : #{params[:ticket]['description']}"
		@ticketConnector.addTicket(params[:ticket]['title'], body, params[:ticket]['appraisal_id'], current_user.id)
		redirect_to(tickets_path, :notice => "Ticket created successfully")
	end

	def show
		@user = current_user
		@ticket = Ticket.where('id = ? and user_id =? ', params[:id], current_user.id).first
		unless @ticket.nil?
			ticketConnector = Complaints::Lighthouse.new()
			@tmTicket = ticketConnector.getTicket(@ticket) 
			@comments = ticketConnector.getComments(@ticket)
		end
	end
end

app/helpers/contact_helper.rb
module ContactHelper
end

app/views/contact/_contact_tabs.html.erb
<ul class="nav nav-tabs">
  <li <%= css_class_for_active_page(path: contact_path) %> ><%= link_to "Contact Support", contact_path %></li>
</ul>

app/views/contact/new.html.erb
<div class="row">
  <div class="col-md-9 col-md-offset-1">
    <div class="big-title">
      Support
    </div>
    <%= render :partial => "contact_tabs" if current_user %>
    <%= simple_form_for @message, :url => contact_path, :html => {:class => 'form-horizontal'}  do |f| %>
      <% if !current_user %>
        <%= f.input :name %>
        <%= f.input :email %>
      <% else %>
        <% @message.email = current_user.email; @message.name = current_user.name %>
        <%= f.input :name, as: :hidden %>
        <%= f.input :email, as: :hidden %>
      <% end %>
      <%= f.input :subject %>
      <%= f.input :body, as: :text, input_html: {:rows => 4 } %>
      <div class="row">
        <div class="col-md-10 col-md-offset-2">
          For phone support call: (925) 289-8746
        </div>
      </div>
      <div>
        <%= tb_submit_button(title: "Send") %>
      </div>
    <% end %>
  </div>
</div>

app/views/contact/show.html.erb
<h4>Customer Support</h4>
<div class="sub_box">
	<%= render :partial => "contact_tabs" %>
	<% if !(@ticket.nil?) %>

		<h3><%= "##{@tmTicket.number} #{@tmTicket.title}" %></h3>
	<div>
		<table class="table table-striped table-hover table table-condensed">
		<tbody>
			<tr>
				<td>Status</td>
				<td><%= @tmTicket.state %></td>
			</tr>
			<tr>
				<td>Created</td>
				<td><%= @tmTicket.created_at %></td>
			</tr>
			<tr>
				<td>Description</td>
				<td><%= simple_format(@tmTicket.latest_body) %></td>
			</tr>
		</tbody>
		</table>
	</div>
	<div>
		<% unless @comments.nil? or @comments.empty? %>
		<table class="table table-striped table-hover table table-condensed">
			<thead>
				<tr>
					<th>Date</th>
					<th>Comment</th>
				</tr>
			</thead>
			<tbody>
				<% @comments.each do |c| %>
				<tr>
					<td><%= c.created_at %></td>
					<td><%= c.body %></td>
				</tr>	
				<% end %>
			</tbody>
		</table>
		<% end %>
	</div>
	<% else %>
	Ticket cannot be found
	<% end %>
</div>

app/views/contact/ticket.html.erb
<h4>New Ticket</h4>
<div class="sub_box">
	<%= simple_form_for(@ticket, :url => ticket_create_path, :method => :post, :html => {:multipart => true, :class => "form-horizontal"}) do |f| %>
	<%= f.input :appraisal_id, :collection => @appraisals, :label => "Please select an appraisal", :label_method => lambda { |appraisal| "##{appraisal.id} - #{appraisal.title} (#{getStringForActivityValue(appraisal.status)})" }, :input_html => {:class => "input-xxlarge"} %>
	<%= f.input :title do |l| %>
		<%= text_field_tag "ticket[title]", nil, :class => "input-xxlarge" %>
	<% end %>
	<%= f.input :description do |l| %>
		<%= text_area_tag "ticket[description]", nil, :rows => 4, :class => "input-xxlarge" %>
	<% end %>
  <div class="form-actions">
  	<%= link_to 'Cancel', tickets_path, :class => "btn" %>
    <%= f.submit "Create ticket", :class => "btn btn-success"%>
  </div>
<% end %>
</div>

app/views/contact/tickets.html.erb
<center>
  <div class="contentBlock">
    <div class="formTop">
      <span class="title41">Support</span><br /><br />
    </div>
    <br />
    <%= render :partial => "contact_tabs" if current_user %>
    <div class="row">
      <%= link_to new_ticket_path, :class => "btn btn-success pull-right" do %><i class="icon-plus icon-white"></i> New Issue <% end %>
    </div>
    <% if @tickets.count > 0 %>
      <table class="table table-striped table-hover table table-condensed">
      <thead>
        <tr>
          <th></th>
          <th>Id</th>
          <th>Created</th>
          <th>Appraisal</th>
          <th>Status</th>
          <th></th>
        </tr>
      </thead>
      <tbody>
      <% @tickets.each do |t| %>
        <% remoteTicket = @ticketConnector.getTicket(t.id)
        unless remoteTicket.nil? %>
      <tr>
          <td><span class="label label-success"><%= raw remoteTicket.closed ? "<i class='icon-folder-close icon-white'></i>" : "<i class='icon-folder-open icon-white'></i>"%></span></td>
          <td><%= remoteTicket.number %></td>
          <td><%= remoteTicket.created_at %></td>
          <td><%= link_to "# #{t.appraisal.id} - #{t.appraisal.title}", appraisal_path(t.appraisal)  %></td>
          <td><%= remoteTicket.state.upcase %></td>
          <td><%= link_to show_ticket_path(t) do %>View <% end %></td>
        </tr>			
      <% end %>
      <% end %>
        </tbody>
      </table>
    <% else %>
        <div class="row">
        <div class="span12">
          You have not created any customer support tickets
        </div>
      </div>
    <% end %>
    </div>
  </center>